<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>nl.hauntedmc.platform</groupId><artifactId>haunted-application-parent</artifactId><version>1.0.1</version><relativePath/></parent><groupId>nl.hauntedmc.platform.verification</groupId><artifactId>application-parent-consumer</artifactId><version>1.0.1</version><packaging>jar</packaging><dependencies><dependency><groupId>nl.hauntedmc.dataprovider</groupId><artifactId>dataprovider-api</artifactId></dependency><dependency><groupId>nl.hauntedmc.theme</groupId><artifactId>hauntedmc-theme-palette</artifactId></dependency></dependencies></project>
