<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.hauntedmc.platform</groupId>
        <artifactId>haunted-parent</artifactId>
        <version>1.6.2</version>
        <relativePath>../haunted-parent/pom.xml</relativePath>
    </parent>
    <artifactId>haunted-library-parent</artifactId>
    <packaging>pom</packaging>
    <name>HauntedPlatform library parent</name>
    <description>Parent for independently reusable HauntedMC libraries.</description>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>nl.hauntedmc.platform</groupId>
                <artifactId>haunted-dependencies-bom</artifactId>
                <version>1.6.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
