<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>nl.hauntedmc.platform</groupId><artifactId>haunted-library-parent</artifactId><version>1.6.1</version><relativePath/></parent><groupId>nl.hauntedmc.platform.verification</groupId><artifactId>library-parent-consumer</artifactId><version>1.6.1</version><packaging>jar</packaging><dependencies><dependency><groupId>io.opentelemetry</groupId><artifactId>opentelemetry-api</artifactId></dependency><dependency><groupId>io.opentelemetry.instrumentation</groupId><artifactId>opentelemetry-runtime-telemetry</artifactId></dependency><dependency><groupId>com.google.code.gson</groupId><artifactId>gson</artifactId></dependency></dependencies><build><plugins><plugin><groupId>org.basepom.maven</groupId><artifactId>duplicate-finder-maven-plugin</artifactId></plugin></plugins></build></project>
